### ISSUE TITLE
How to use Epicc to watch Intent values?

### ISSUE THREAD

**Issue by ZhengqiaoLi** [siis/ic3#11]
My apk are as follows：
1.MainActivity:
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

```
    btn = (Button)findViewById(R.id.btn);
    btn.setOnClickListener(new View.OnClickListener() {

        @Override
        public void onClick(View arg0) {
            // TODO Auto-generated method stub
            Intent intent = new Intent();
            intent.setClass(MainActivity.this, second.class);
            startActivity(intent);
            MainActivity.this.finish();
        }
    });
}
```

2.second:
        btn = (Button)findViewById(R.id.btn);
        btn.setOnClickListener(new Button.OnClickListener(){

```
        @Override
        public void onClick(View arg0) {
            // TODO Auto-generated method stub
            Intent intent = new Intent();
            intent.setClass(second.this,third.class);
            startActivity(intent);
            second.this.finish();
        }});
}
```

3.third:
public class third extends Activity {

```
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.third);
}

@Override
public boolean onCreateOptionsMenu(Menu menu) {
    // Inflate the menu; this adds items to the action bar if it is present.
    getMenuInflater().inflate(R.menu.main, menu);
    return true;
}
```

}

Then,I use Dare and Epicc.The results are as follows:

[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
[Call Graph] For information on where the call graph may be incomplete, use the verbose option to the cg phase.
[Spark] Pointer Assignment Graph in 0.0 seconds.
[Spark] Type masks in 0.0 seconds.
[Spark] Pointer Graph simplified in 0.0 seconds.
[Spark] Propagation in 0.0 seconds.
[Spark] Solution found in 0.0 seconds.
Solving ICC problem
Composing values

Manifest file for com.example.hello version 1
  Activities:
    com.example.hello.MainActivity
      Intent filter:
        Actions: [android.intent.action.MAIN]
        Categories: [android.intent.category.LAUNCHER]
    com.example.hello.second
    com.example.hello.third

  Activity Aliases:
  Services:
  Receivers:
  Providers:

The following ICC values were found:
febbie@febbie-OptiPlex-960:~/Documents/小论文相关工具/epicc-0.1$ 

I want to know where are Intent values of codes?
please!
thank you!

**Comment by ZhengqiaoLi** [comment]
It works.
I am stupid.

**Comment by jxnu707** [comment]
hi，
鼓捣了几天，还是跑不起来，能帮帮忙么？
