### ISSUE TITLE
Fail to launch IC3 

### ISSUE THREAD

**Issue by jxnu707** [siis/ic3#13]
hi,
I launched IC3 using：
D:\test>java -Xmx4g -jar ic3.jar -apkormanifest test.apk -input class -cp android.jar
here's the content under the D:\test
![image](https://cloud.githubusercontent.com/assets/5088377/11954763/117aa5d0-a8e6-11e5-8816-cdd6e5db024b.png)
there is some .class files in test/class/
![image](https://cloud.githubusercontent.com/assets/5088377/11954772/1f93c476-a8e6-11e5-8239-981f16f7f172.png)
but I failed to launch it with soot.CompilationDeathException:Couldn't resolve classpath entry android.jar:class:
In addition,I run soot for retargeting and get some .class files from a apk like above in test/class/.
                                "-src-prec","apk",
                "-android-jars","D:\work\adt\adt\sdk\platforms",
                "-f","c",
                "-cp",classpath,
                "-process-dir",sootInput_android,
                "-d",sootOutput};
Is there some difference from Dare and lead to that Exception?

**Comment by docteau** [comment]
Hi,

Were you able to resolve this? Have you also tried using Dare for retargeting?

**Comment by jxnu707** [comment]
Hi,
Thanks for help!
I used Dare for retargeting and got some classes files in retargeted/<app_name> subdirectory which be uesed as the input of IC3.
But I got the same problem like #12 ,here was the command line I uesd:
![image](https://cloud.githubusercontent.com/assets/5088377/12385580/a098dc56-bdf8-11e5-9453-61f64306751f.png)
Did I make some mistake with the apkormanfiest option?

**Comment by jxnu707** [comment]
Further more, there is an AndroidManifest.xml file in test.apk,and as the source code of IC3:
![image](https://cloud.githubusercontent.com/assets/5088377/12386106/7647b4d6-bdfd-11e5-8c7f-f5eb6258f358.png)
these two exceptions were not catched,so it seems not the appPath problem.
I really appreciate your help.

**Comment by docteau** [comment]
Hi,

What is your operating system? It looks like you are using a different setup in your latest screenshot. Are you getting the same CompilationDeathException?

**Comment by jxnu707** [comment]
Hi,

1) I run the IC3 in linux(both Ubuntu and CentOS),it came to the same result(NullPointerException).
2) And I read the source in windows eclipse.
3) I get the ic3.jar from your website: http://siis.cse.psu.edu/ic3/downloads.html and install as the 
    instructions.
4) I never got any CompilationDeathException, what is that?

Thanks!

**Comment by docteau** [comment]
In your first message you mentioned sootCompilationDeathException.

Can you copy and paste the entire error message?

**Comment by jxnu707** [comment]
Hi,
I use Dare instead of Soot,as your advice.

**Comment by jxnu707** [comment]
I figure it out
Thanks for your help
Close it now
