### ISSUE TITLE
What does the "Components" in output represent?

### ISSUE THREAD

**Issue by 0-14N** [siis/ic3#2]
Hi,

I am curious what does the "Components" (e.g. Components: [class1, class2, ...]) represent?
Thanks.

**Comment by docteau** [comment]
Hi,

They are the Android components that are sending a particular ICC message, i.e., the source components of an inter-component communication.

**Comment by Sandm-HY** [comment]
I am curious what does the "exported"(eg:exported: true) represent?
Could you tell me,please.
