### ISSUE TITLE
Can not find edu.psu.cse.siis.ic3.Ic3Data;

### ISSUE THREAD

**Issue by snowcool** [siis/ic3#23]
Dear developers:

I am trying to run IC3 from Eclipse,  but the source code could not find 
import edu.psu.cse.siis.ic3.Ic3Data;
import edu.psu.cse.siis.ic3.Ic3Data.Application.Builder;
import edu.psu.cse.siis.ic3.Ic3Data.Application.Component;
import edu.psu.cse.siis.ic3.Ic3Data.Application.Component.ComponentKind;
import edu.psu.cse.siis.ic3.Ic3Data.Application.Component.IntentFilter;
import edu.psu.cse.siis.ic3.Ic3Data.Attribute;
import edu.psu.cse.siis.ic3.Ic3Data.AttributeKind;

I wonder how can i fix it.
Thank you very much!

**Comment by g252691665** [comment]
it is a maven project,you should run maven build/maven clean/maven install，The premise is that your eclipse installed Maven plugin.

**Comment by snowcool** [comment]
Thank you very much~
Best wishes.

**Comment by snowcool** [comment]
Hello,
here again, sorry for disturbing.
When I run apks in ICC-Bench-master, there has some problems occurred that cannot go on the analysis.
Soot started on Thu Feb 02 08:47:14 CST 2017
Using '/raid/workspace/xueshuangshuang/sootworkplace/android-platforms/android-21/android.jar' as android.jar
/raid/workspace/xueshuangshuang/sootworkplace/soot/tests/soot/RefTypeTest.java:4,8:
  Semantic Error: no visible type named org.junit.Assert
/raid/workspace/xueshuangshuang/sootworkplace/soot/tests/soot/RefTypeTest.java:5,8:
  Semantic Error: no visible type named org.junit.Test
/raid/workspace/xueshuangshuang/sootworkplace/soot/tests/soot/RefTypeTest.java:9,3:
  Semantic Error: no visible type named Test
/raid/workspace/xueshuangshuang/sootworkplace/soot/tests/soot/RefTypeTest.java:11,3:
  Semantic Error: G not found
/raid/workspace/xueshuangshuang/sootworkplace/soot/tests/soot/RefTypeTest.java:13,3:
  Semantic Error: Scene not found
/raid/workspace/xueshuangshuang/sootworkplace/soot/tests/soot/RefTypeTest.java:15,3:
  Semantic Error: no visible type named SootClass
/raid/workspace/xueshuangshuang/sootworkplace/soot/tests/soot/RefTypeTest.java:15:
  Semantic Error: can not instantiate Unknown no matching constructor found in Unknown
.......

I wonder how can this happen.
Thank you very much~
Best wishes.

**Comment by snowcool** [comment]
Besides, when I run IC3 through eclipse, there is no /res/icc.cmodel file, so: 
Exception in thread "main" java.lang.NullPointerException
	at java.io.ObjectInputStream$PeekInputStream.read(Unknown Source)
	at java.io.ObjectInputStream$PeekInputStream.readFully(Unknown Source)
	at java.io.ObjectInputStream$BlockDataInputStream.readShort(Unknown Source)
	at java.io.ObjectInputStream.readStreamHeader(Unknown Source)
	at java.io.ObjectInputStream.<init>(Unknown Source)
	at edu.psu.cse.siis.coal.Model.loadModelFromCompiledFile(Model.java:172)
	at edu.psu.cse.siis.coal.Analysis.loadModel(Analysis.java:90)
	at edu.psu.cse.siis.coal.Analysis.performAnalysis(Analysis.java:58)
	at edu.psu.cse.siis.ic3.Main.main(Main.java:22)
	at edu.psu.cse.siis.ic3.Test.main(Test.java:43)

I wonder where can I find /res/icc.cmodel ?
