### ISSUE TITLE
Where is the "/res/icc.cmodel"?

### ISSUE THREAD

**Issue by fripSide** [siis/ic3#8]
I try to compile IC3 with newest version of Soot and FlowDroid. But lots of files are missing, such as the icc.cmodel. In you release file ic3-full.jar these files exits but I can't find these files in github.

**Comment by docteau** [comment]
Hi,

What commands did you use to perform the compilation? File icc.cmodel should be automatically generated by Maven from the files in src/main/resources/model.

Best,
Damien

**Comment by fripSide** [comment]
Thank you for your instructing. I have solved the problem using Maven Build. Serval days ago, I just import the project to Intelij IDEA and remove the Maven files and replace some of the dependencies, so I failed to generate the model and "edu.psu.cse.siis.coal.lang" package. This time I complied successfully by importing he maven projects and using maven build commands.
