### ISSUE TITLE
Run IC3

### ISSUE THREAD

**Issue by Mac85** [siis/ic3#9]
Hi
please let you tell me what I need to do to launch IC3?

IC3 can be launched using: 
% java [JVM options] -jar <path to IC3 Jar> -apkormanifest <path to .apk> \
-input <path to retargeted application> -cp <path to Android Jar> [IC3 options]

you can explain to me the paths of which files I have to add? Thank's

**Comment by docteau** [comment]
Hi,

After -jar, please use the path to the IC3 Jar file (extracted from one of the downloads from http://siis.cse.psu.edu/ic3/downloads.html). After -apkormanifest, use the path to the application apk you would like to analyze. After -input, include the path to the retargeted application (see http://siis.cse.psu.edu/dare/ for more information about retargeting). After -cp, use the path to the Android Jar that you have also downloaded from from http://siis.cse.psu.edu/ic3/downloads.html).

**Comment by Mac85** [comment]
Hi Damien
thank’s for your reply.
But : “After -input, include the path to the retargeted application” ?? I have this path(to see image)

Which file do I have to select in the folder?

**Comment by Mac85** [comment]
Now it works :)
Thank's

**Comment by jxnu707** [comment]
hi,
  I still have some problems with the command lines to launch ic3
  "--input","D:\\test\\zaker\\retargeted\\",
  "-cp","D:\\test\\android.jar",
  "-apkormanifest", "D:\\test\\zaker.apk"	
  could you help me with it?
